name: Generate Markdown JavaDoc

on:
  push:
    branches:
      - experimental
  workflow_dispatch:

jobs:
  build-and-package-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 镜像不安全的 Jenkins HTTP 仓库 !!!
      - name: Create settings.xml for Maven
        run: |
          mkdir -p ~/.m2
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
              <mirrors>
                <mirror>
                  <id>jenkins-repo-secure</id>
                  <mirrorOf>repo.jenkins-ci.org</mirrorOf>
                  <url>https://repo.jenkins-ci.org/public/</url>
                </mirror>
              </mirrors>
            </settings>' > ~/.m2/settings.xml

      - name: Generate Markdown JavaDoc with Maven
        run: mvn -B --settings ~/.m2/settings.xml javadoc:javadoc

      - name: Zip the documentation
        run: zip -r javadoc-markdown.zip target/apidocs-md

      - name: Upload Javadoc Artifact
        uses: actions/upload-artifact@v4
        with:
          name: javadoc-markdown-docs
          path: javadoc-markdown.zip